INSERT INTO `SOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('BBBBBB01A01A001A', 'PROVA', 'COGNOME', 'M', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'CELIBE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `SOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('CCCCCC01A01A001A', 'PROVA', 'COGNOME', 'F', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'NUBILE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `SOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('DDDDDD01A01A001A', 'PROVA', 'COGNOME', 'M', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'CELIBE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `SOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('EEEEEE01A01A001A', 'PROVA', 'COGNOME', 'F', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'NUBILE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `SOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('FFFFFF01A01A001A', 'PROVA', 'COGNOME', 'M', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'CELIBE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');


INSERT INTO `EXSOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('IIIIII01A01A001A', 'PROVA', 'COGNOME', 'M', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'CELIBE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `EXSOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('LLLLLL01A01A001A', 'PROVA', 'COGNOME', 'F', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'NUBILE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `EXSOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('MMMMMM01A01A001A', 'PROVA', 'COGNOME', 'M', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'CELIBE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `EXSOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('NNNNNN01A01A001A', 'PROVA', 'COGNOME', 'F', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'NUBILE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `EXSOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('OOOOOO01A01A001A', 'PROVA', 'COGNOME', 'M', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'CELIBE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO EVENTO (NOME, DATA, DESCRIZIONE, N_POSTI, LUOGO, PREZZO) 
VALUES ('FESTA', '2015-05-05', 'è UNA FESTA DEL SESSO', 130, "FACOLTA' DI INGEGNERIA", 22.30);

INSERT INTO EVENTO (NOME, DATA, DESCRIZIONE, N_POSTI, LUOGO, PREZZO) 
VALUES ('ORGIA', '2017-09-09', 'è UNA ORGIA PER SOLE DONNE', 5, 'VIA NAPOLI 2', 120.50);

INSERT INTO `NONSOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `EMAIL`, `TELEFONO`) 
VALUES ('PPPPPP01A01A001A', 'PROVA', 'COGNOME', 'F', 'PROVA@PROVA.IT', '3333333333');

INSERT INTO `SALA` (`NOME`, `CAPIENZA`, `DESCRIZIONE`, `TARIFFA`) 
VALUES ('NERI', 50, 'è una sala di merda piena di robe schifose', 120.50);

INSERT INTO `SALA` (`NOME`, `CAPIENZA`, `DESCRIZIONE`, `TARIFFA`) 
VALUES ('VERDI', 55, 'è una sala che costa due euro di più della neri perchè è verdi', 122.30);

INSERT INTO `SALA` (`NOME`, `CAPIENZA`, `DESCRIZIONE`, `TARIFFA`) 
VALUES ('SKRONOPOF', 50, 'è una sala ed è già tanto', 120.00);

INSERT INTO `SALA` (`NOME`, `CAPIENZA`, `DESCRIZIONE`, `TARIFFA`) 
VALUES ('BRAZOF', 60, 'è una sala enorme ma che costa poco perchè confina con la mensa dei poveri piena di zingari', 135.50);

INSERT INTO `SALA` (`NOME`, `CAPIENZA`, `DESCRIZIONE`, `TARIFFA`) 
VALUES ('BENITO MUSSOLINI', 44, 'è la sal più piccola e stretta del circolo pare un bucio di culo', 117.90);

INSERT INTO `SALA` (`NOME`, `CAPIENZA`, `DESCRIZIONE`, `TARIFFA`) 
VALUES ('DUX MEA LUX', 55, 'è una costosissima ma senza un cazzo dentro', 180.00);

INSERT INTO FIGLIO (CF, NOME, SESSO, DATA_NASCITA, ACARICO, GENITORE) 
VALUES ('NNNNNN01A01A024C', 'MARCO', 'M', '2001-07-07', 1,'FFFFFF01A01A001A');

INSERT INTO FIGLIO (CF, NOME, SESSO, DATA_NASCITA, ACARICO, GENITORE)  
VALUES ('AABBCO01A01A001A', 'CECILIA', 'F', '1995-12-23', 1, 'EEEEEE01A01A001A');