INSERT INTO `SOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('BBBBBB01A01A001A', 'PROVA', 'COGNOME', 'M', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'CELIBE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `SOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('CCCCCC01A01A001A', 'PROVA', 'COGNOME', 'F', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'NUBILE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `SOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('DDDDDD01A01A001A', 'PROVA', 'COGNOME', 'M', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'CELIBE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `SOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('EEEEEE01A01A001A', 'PROVA', 'COGNOME', 'F', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'NUBILE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `SOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('FFFFFF01A01A001A', 'PROVA', 'COGNOME', 'M', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'CELIBE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');


INSERT INTO `EXSOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('IIIIII01A01A001A', 'PROVA', 'COGNOME', 'M', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'CELIBE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `EXSOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('LLLLLL01A01A001A', 'PROVA', 'COGNOME', 'F', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'NUBILE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `EXSOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('MMMMMM01A01A001A', 'PROVA', 'COGNOME', 'M', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'CELIBE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `EXSOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('NNNNNN01A01A001A', 'PROVA', 'COGNOME', 'F', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'NUBILE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');

INSERT INTO `EXSOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `DATA_NASCITA`, `LUOGO_NASCITA`, `INDIRIZZO`, `CITTA`, `CAP`, `EMAIL`, 
`TELEFONO`, `PROFESSIONE`, `STATO_CIVILE`, `CONIUGE`, `DATA_AMMISSIONE`, `TASSA_AMMISSIONE`, `MOD_PAGAMENTO`, `MET_PAGAMENTO`, `TIPOLOGIA`)
VALUES ('OOOOOO01A01A001A', 'PROVA', 'COGNOME', 'M', '1963-03-17', 'ASCOLI PICENO', 'VIA DEI FIORI', 'ASCOLI PICENO', '63100', 'PROVA@PROVA.IT',
'3333333333', 'STUDENTE', 'CELIBE', NULL, '2000-02-05', 200.00, 'ANNUALE', 'ESATTORE', 'ORDINARIO');



INSERT INTO `NONSOCIO` (`CF`, `NOME`, `COGNOME`, `SESSO`, `EMAIL`, `TELEFONO`) 
VALUES ('PPPPPP01A01A001A', 'PROVA', 'COGNOME', 'F', 'PROVA@PROVA.IT', '3333333333');